//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationGuidance_service.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperationGuidance_service.Database.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : AnengDB
        /// Source Server Type    : MySQL
        /// Source Server Version : 50744
        /// Source Host           : localhost:3307
        /// Source Schema         : aneng
        ///
        /// Target Server Type    : MySQL
        /// Target Server Version : 50744
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:44:48
        ///*/
        ///
        ///SET NAMES utf8mb4;
        ///SET FOREIGN_KEY_CHECKS = 0;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_mysql {
            get {
                return ResourceManager.GetString("init_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : SQLite
        /// Source Server Type    : SQLite
        /// Source Server Version : 3030001
        /// Source Schema         : main
        ///
        /// Target Server Type    : SQLite
        /// Target Server Version : 3030001
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:27:07
        ///*/
        ///
        ///PRAGMA foreign_keys = false;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;bar_code_matching_rule&quot;;
        ///CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_sqlite {
            get {
                return ResourceManager.GetString("init_sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `predecessor_mission_id` int NULL AFTER `macs_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240407 {
            get {
                return ResourceManager.GetString("modify_mysql_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `multi_device_independence` int(1) NULL AFTER `predecessor_mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240413 {
            get {
                return ResourceManager.GetString("modify_mysql_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_side` 
        ///  ADD COLUMN `cropped` int(1) NULL AFTER `rotate_angle`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240510 {
            get {
                return ResourceManager.GetString("modify_mysql_20240510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for outer_database_config
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `outer_database_config`;
        ///CREATE TABLE `outer_database_config`  (
        ///  `id` int(11) NOT NULL AUTO_INCREMENT,
        ///  `host` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `port` int(8) NULL DEFAULT NULL,
        ///  `database_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `username` varchar(255) CHARACTER SET utf8m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240515 {
            get {
                return ResourceManager.GetString("modify_mysql_20240515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for device_io
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `device_io`;
        ///CREATE TABLE `device_io`  (
        ///  `id` int(11) NOT NULL AUTO_INCREMENT,
        ///  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `ip` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `port` int(8) NULL DEFAULT N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240517 {
            get {
                return ResourceManager.GetString("modify_mysql_20240517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_bolt` 
        ///  ADD COLUMN `arranger_id` int(11) NULL AFTER `name`,
        ///  ADD COLUMN `setter_selector_id` int(11) NULL AFTER `location_y_percent`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240521 {
            get {
                return ResourceManager.GetString("modify_mysql_20240521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `predecessor_part_mission_ids` varchar(256) NULL AFTER `predecessor_mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240531 {
            get {
                return ResourceManager.GetString("modify_mysql_20240531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_bolt` 
        ///  ADD COLUMN `arranger_id2` int NULL AFTER `specification`,
        ///  ADD COLUMN `specification2` double NULL AFTER `arranger_id2`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240606 {
            get {
                return ResourceManager.GetString("modify_mysql_20240606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for curve_data
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `curve_data`;
        ///CREATE TABLE `curve_data`  (
        ///  `id` int NOT NULL AUTO_INCREMENT,
        ///  `operation_data_id` int NOT NULL,
        ///  `result_data_identifier` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        ///  `time_stamp` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        ///  `data_type` int NOT NULL,
        ///  `data_samples` longtext CHARACTER SET utf8mb4 COLLATE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240614 {
            get {
                return ResourceManager.GetString("modify_mysql_20240614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `outer_database_config` 
        ///  RENAME `outer_database_config_glb`,
        ///  ADD COLUMN `workstation_name` varchar(128) NULL AFTER `database_type`,
        ///  ADD COLUMN `macs_id` int(11) NULL AFTER `workstation_name`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240618 {
            get {
                return ResourceManager.GetString("modify_mysql_20240618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240407&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240407 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240413&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240413 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_side&quot; RENAME TO &quot;_product_side_old_20240510&quot;;
        ///
        ///CREATE TABLE &quot;product_side&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;mission_id&quot; integer,
        ///  &quot;image&quot; text(256),
        ///  &quot;max_rectangle_width&quot; integer(16),
        ///  &quot;max_rectangle_height&quot; integer(16),
        ///  &quot;max_rectangle_location&quot; text(32),
        ///  &quot;center_location&quot; text(32),
        ///  &quot;location_offset&quot; text(32),
        ///  &quot;location_offset_moving&quot; text(32),
        ///  &quot;zooming_ratio&quot; real(8),
        ///  &quot;zooming_ratio_extra&quot; real(8),
        ///  &quot;rotate_angl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240510 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for outer_database_config
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;outer_database_config&quot;;
        ///CREATE TABLE &quot;outer_database_config&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;host&quot; text(64),
        ///  &quot;port&quot; integer(8),
        ///  &quot;database_name&quot; text(255),
        ///  &quot;username&quot; text(255),
        ///  &quot;password&quot; text(255),
        ///  &quot;database_type&quot; integer(2),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240515 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for device_io
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;device_io&quot;;
        ///CREATE TABLE &quot;device_io&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;description&quot; text(512),
        ///  &quot;ip&quot; text(16),
        ///  &quot;port&quot; integer(8),
        ///  &quot;type&quot; integer(4),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) NOT NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240517 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_bolt&quot; RENAME TO &quot;_product_bolt_old_20240521&quot;;
        ///
        ///CREATE TABLE &quot;product_bolt&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;side_id&quot; integer NOT NULL,
        ///  &quot;serial_num&quot; integer NOT NULL,
        ///  &quot;name&quot; text(128),
        ///  &quot;arranger_id&quot; integer,
        ///  &quot;specification&quot; real(16),
        ///  &quot;workstation_id&quot; integer,
        ///  &quot;position&quot; text(32),
        ///  &quot;location_x_percent&quot; real(8) NOT NULL,
        ///  &quot;location_y_percent&quot; real(8) NOT NULL,
        ///  &quot;setter_selector_id&quot; integer,
        ///  &quot;bit_specification&quot; real(16),
        ///  &quot;parameters_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240521 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240531&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;predecessor_part_mission_ids&quot; text(256),
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240531 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_bolt&quot; RENAME TO &quot;_product_bolt_old_20240606&quot;;
        ///
        ///CREATE TABLE &quot;product_bolt&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;side_id&quot; integer NOT NULL,
        ///  &quot;serial_num&quot; integer NOT NULL,
        ///  &quot;name&quot; text(128),
        ///  &quot;arranger_id&quot; integer,
        ///  &quot;specification&quot; real(16),
        ///  &quot;arranger_id2&quot; integer,
        ///  &quot;specification2&quot; real(16),
        ///  &quot;workstation_id&quot; integer,
        ///  &quot;position&quot; text(32),
        ///  &quot;location_x_percent&quot; real(8) NOT NULL,
        ///  &quot;location_y_percent&quot; real(8) NOT NULL,
        ///  &quot;setter_selector_id&quot; i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240606 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for curve_data
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;curve_data&quot;;
        ///CREATE TABLE &quot;curve_data&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;operation_data_id&quot; integer NOT NULL,
        ///  &quot;result_data_identifier&quot; text(64) NOT NULL,
        ///  &quot;time_stamp&quot; text(64) NOT NULL,
        ///  &quot;data_type&quot; integer(2) NOT NULL,
        ///  &quot;data_samples&quot; text NOT NULL,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240614 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE outer_database_config RENAME TO outer_database_config_glb;
        ///ALTER TABLE &quot;outer_database_config_glb&quot; RENAME TO &quot;_outer_database_config_glb_old_20240618&quot;;
        ///
        ///CREATE TABLE &quot;outer_database_config_glb&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;host&quot; text(64),
        ///  &quot;port&quot; integer(8),
        ///  &quot;database_name&quot; text(255),
        ///  &quot;username&quot; text(255),
        ///  &quot;password&quot; text(255),
        ///  &quot;database_type&quot; integer(2),
        ///  &quot;workstation_name&quot; text(128),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;delete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240618 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240618", resourceCulture);
            }
        }
    }
}
