//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationGuidance_service.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperationGuidance_service.Database.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : AnengDB
        /// Source Server Type    : MySQL
        /// Source Server Version : 50744
        /// Source Host           : localhost:3307
        /// Source Schema         : aneng
        ///
        /// Target Server Type    : MySQL
        /// Target Server Version : 50744
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:44:48
        ///*/
        ///
        ///SET NAMES utf8mb4;
        ///SET FOREIGN_KEY_CHECKS = 0;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_mysql {
            get {
                return ResourceManager.GetString("init_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : SQLite
        /// Source Server Type    : SQLite
        /// Source Server Version : 3030001
        /// Source Schema         : main
        ///
        /// Target Server Type    : SQLite
        /// Target Server Version : 3030001
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:27:07
        ///*/
        ///
        ///PRAGMA foreign_keys = false;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;bar_code_matching_rule&quot;;
        ///CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_sqlite {
            get {
                return ResourceManager.GetString("init_sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : SqlServer_OperationGuidanceNew
        /// Source Server Type    : SQL Server
        /// Source Server Version : 16001000
        /// Source Host           : 127.0.0.1:1433
        /// Source Catalog        : aneng
        /// Source Schema         : dbo
        ///
        /// Target Server Type    : SQL Server
        /// Target Server Version : 16001000
        /// File Encoding         : 65001
        ///
        /// Date: 20/06/2024 22:02:14
        ///*/
        ///
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- --------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_sqlserver {
            get {
                return ResourceManager.GetString("init_sqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `predecessor_mission_id` int NULL AFTER `macs_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240407 {
            get {
                return ResourceManager.GetString("modify_mysql_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `multi_device_independence` int(1) NULL AFTER `predecessor_mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240413 {
            get {
                return ResourceManager.GetString("modify_mysql_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_side` 
        ///  ADD COLUMN `cropped` int(1) NULL AFTER `rotate_angle`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240510 {
            get {
                return ResourceManager.GetString("modify_mysql_20240510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for outer_database_config
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `outer_database_config`;
        ///CREATE TABLE `outer_database_config`  (
        ///  `id` int(11) NOT NULL AUTO_INCREMENT,
        ///  `host` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `port` int(8) NULL DEFAULT NULL,
        ///  `database_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `username` varchar(255) CHARACTER SET utf8m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240515 {
            get {
                return ResourceManager.GetString("modify_mysql_20240515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for device_io
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `device_io`;
        ///CREATE TABLE `device_io`  (
        ///  `id` int(11) NOT NULL AUTO_INCREMENT,
        ///  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `ip` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        ///  `port` int(8) NULL DEFAULT N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240517 {
            get {
                return ResourceManager.GetString("modify_mysql_20240517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_bolt` 
        ///  ADD COLUMN `arranger_id` int(11) NULL AFTER `name`,
        ///  ADD COLUMN `setter_selector_id` int(11) NULL AFTER `location_y_percent`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240521 {
            get {
                return ResourceManager.GetString("modify_mysql_20240521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `predecessor_part_mission_ids` varchar(256) NULL AFTER `predecessor_mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240531 {
            get {
                return ResourceManager.GetString("modify_mysql_20240531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_bolt` 
        ///  ADD COLUMN `arranger_id2` int NULL AFTER `specification`,
        ///  ADD COLUMN `specification2` double NULL AFTER `arranger_id2`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240606 {
            get {
                return ResourceManager.GetString("modify_mysql_20240606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for curve_data
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `curve_data`;
        ///CREATE TABLE `curve_data`  (
        ///  `id` int NOT NULL AUTO_INCREMENT,
        ///  `operation_data_id` int NOT NULL,
        ///  `result_data_identifier` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        ///  `time_stamp` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        ///  `data_type` int NOT NULL,
        ///  `data_samples` longtext CHARACTER SET utf8mb4 COLLATE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240614 {
            get {
                return ResourceManager.GetString("modify_mysql_20240614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `outer_database_config` 
        ///  RENAME `outer_database_config_glb`,
        ///  ADD COLUMN `workstation_name` varchar(128) NULL AFTER `database_type`,
        ///  ADD COLUMN `macs_id` int(11) NULL AFTER `workstation_name`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240618 {
            get {
                return ResourceManager.GetString("modify_mysql_20240618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for screw_bit_counter
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `screw_bit_counter`;
        ///CREATE TABLE `screw_bit_counter`  (
        ///  `id` int NOT NULL AUTO_INCREMENT,
        ///  `mission_id` int NOT NULL,
        ///  `bit_position` int NOT NULL,
        ///  `max_num` int NOT NULL,
        ///  `count_each_time` int NOT NULL,
        ///  `current_counts` int NOT NULL,
        ///  `clear_times` int NOT NULL,
        ///  `user_id` int NOT NULL,
        ///  `deleted` int NOT NULL,
        ///  `creator` varchar(128) CHARACTER SET utf8m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240627 {
            get {
                return ResourceManager.GetString("modify_mysql_20240627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `bar_code_matching_rule` 
        ///  ADD COLUMN `name` varchar(64) NULL AFTER `id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240628 {
            get {
                return ResourceManager.GetString("modify_mysql_20240628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_bolt` 
        ///  ADD COLUMN `parts_bar_code_ids` varchar(64) NULL AFTER `angle_max`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240822 {
            get {
                return ResourceManager.GetString("modify_mysql_20240822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for mat_code_map_whyc
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `mat_code_map_whyc`;
        ///CREATE TABLE `mat_code_map_whyc`  (
        ///  `id` int NOT NULL AUTO_INCREMENT,
        ///  `mat_code` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        ///  `parameter_set` int NOT NULL,
        ///  `macs_id` int(8) NULL DEFAULT NULL,
        ///  `user_id` int NOT NULL,
        ///  `deleted` int NOT NULL,
        ///  `creator` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20240828 {
            get {
                return ResourceManager.GetString("modify_mysql_20240828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `is_challenge_mission` int(1) NULL AFTER `multi_device_independence`;
        ///ALTER TABLE `product_mission` 
        ///  ADD COLUMN `is_first_mission` int(1) NULL AFTER `is_challenge_mission`;
        ///ALTER TABLE `product_mission` 
        ///  ADD COLUMN `challenge_mission_id` int(11) NULL AFTER `is_first_mission`;
        ///.
        /// </summary>
        internal static string modify_mysql_20250315 {
            get {
                return ResourceManager.GetString("modify_mysql_20250315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- operation_data
        ///SET @sql := IF(
        ///    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS 
        ///     WHERE TABLE_SCHEMA = DATABASE() 
        ///     AND TABLE_NAME = &apos;operation_data&apos; 
        ///     AND INDEX_NAME = &apos;idx_operation_data_deleted_user_id&apos;) = 0,
        ///    &apos;CREATE INDEX idx_operation_data_deleted_user_id ON operation_data(deleted, user_id, id)&apos;,
        ///    &apos;SELECT &apos;&apos;index idx_operation_data_deleted_user_id already exists, skip this&apos;&apos; AS message&apos;
        ///);
        ///PREPARE stmt FROM @sql;
        ///EXECUTE stmt;
        ///DEALLOCATE PREPARE stmt;
        ///
        ///-- missi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20250625 {
            get {
                return ResourceManager.GetString("modify_mysql_20250625", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ===============
        ///-- 1. 创建数字辅助表 (仅需一次)
        ///-- ===============
        ///DROP TABLE IF EXISTS numbers;
        ///CREATE TABLE numbers (n INT PRIMARY KEY);
        ///
        ///-- 生成 1 到 1000 的数字（可根据需要调整上限）
        ///INSERT INTO numbers (n)
        ///SELECT @row := @row + 1
        ///FROM (
        ///    SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
        ///    SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
        ///) t1,
        ///(
        ///    SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_mysql_20250625_1 {
            get {
                return ResourceManager.GetString("modify_mysql_20250625_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `aneng`.`device_io` 
        ///  ADD COLUMN `barcode` varchar(512) NULL AFTER `type`;
        ///
        ///ALTER TABLE `aneng`.`bar_code_matching_rule` 
        ///  ADD COLUMN `part_no` varchar(128) NULL AFTER `mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20251022 {
            get {
                return ResourceManager.GetString("modify_mysql_20251022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240407&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240407 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240413&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240413 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_side&quot; RENAME TO &quot;_product_side_old_20240510&quot;;
        ///
        ///CREATE TABLE &quot;product_side&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;mission_id&quot; integer,
        ///  &quot;image&quot; text(256),
        ///  &quot;max_rectangle_width&quot; integer(16),
        ///  &quot;max_rectangle_height&quot; integer(16),
        ///  &quot;max_rectangle_location&quot; text(32),
        ///  &quot;center_location&quot; text(32),
        ///  &quot;location_offset&quot; text(32),
        ///  &quot;location_offset_moving&quot; text(32),
        ///  &quot;zooming_ratio&quot; real(8),
        ///  &quot;zooming_ratio_extra&quot; real(8),
        ///  &quot;rotate_angl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240510 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for outer_database_config
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;outer_database_config&quot;;
        ///CREATE TABLE &quot;outer_database_config&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;host&quot; text(64),
        ///  &quot;port&quot; integer(8),
        ///  &quot;database_name&quot; text(255),
        ///  &quot;username&quot; text(255),
        ///  &quot;password&quot; text(255),
        ///  &quot;database_type&quot; integer(2),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240515 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for device_io
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;device_io&quot;;
        ///CREATE TABLE &quot;device_io&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;description&quot; text(512),
        ///  &quot;ip&quot; text(16),
        ///  &quot;port&quot; integer(8),
        ///  &quot;type&quot; integer(4),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) NOT NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240517 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_bolt&quot; RENAME TO &quot;_product_bolt_old_20240521&quot;;
        ///
        ///CREATE TABLE &quot;product_bolt&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;side_id&quot; integer NOT NULL,
        ///  &quot;serial_num&quot; integer NOT NULL,
        ///  &quot;name&quot; text(128),
        ///  &quot;arranger_id&quot; integer,
        ///  &quot;specification&quot; real(16),
        ///  &quot;workstation_id&quot; integer,
        ///  &quot;position&quot; text(32),
        ///  &quot;location_x_percent&quot; real(8) NOT NULL,
        ///  &quot;location_y_percent&quot; real(8) NOT NULL,
        ///  &quot;setter_selector_id&quot; integer,
        ///  &quot;bit_specification&quot; real(16),
        ///  &quot;parameters_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240521 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240531&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;predecessor_part_mission_ids&quot; text(256),
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240531 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_bolt&quot; RENAME TO &quot;_product_bolt_old_20240606&quot;;
        ///
        ///CREATE TABLE &quot;product_bolt&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;side_id&quot; integer NOT NULL,
        ///  &quot;serial_num&quot; integer NOT NULL,
        ///  &quot;name&quot; text(128),
        ///  &quot;arranger_id&quot; integer,
        ///  &quot;specification&quot; real(16),
        ///  &quot;arranger_id2&quot; integer,
        ///  &quot;specification2&quot; real(16),
        ///  &quot;workstation_id&quot; integer,
        ///  &quot;position&quot; text(32),
        ///  &quot;location_x_percent&quot; real(8) NOT NULL,
        ///  &quot;location_y_percent&quot; real(8) NOT NULL,
        ///  &quot;setter_selector_id&quot; i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240606 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for curve_data
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;curve_data&quot;;
        ///CREATE TABLE &quot;curve_data&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;operation_data_id&quot; integer NOT NULL,
        ///  &quot;result_data_identifier&quot; text(64) NOT NULL,
        ///  &quot;time_stamp&quot; text(64) NOT NULL,
        ///  &quot;data_type&quot; integer(2) NOT NULL,
        ///  &quot;data_samples&quot; text NOT NULL,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240614 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE outer_database_config RENAME TO outer_database_config_glb;
        ///ALTER TABLE &quot;outer_database_config_glb&quot; RENAME TO &quot;_outer_database_config_glb_old_20240618&quot;;
        ///
        ///CREATE TABLE &quot;outer_database_config_glb&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;host&quot; text(64),
        ///  &quot;port&quot; integer(8),
        ///  &quot;database_name&quot; text(255),
        ///  &quot;username&quot; text(255),
        ///  &quot;password&quot; text(255),
        ///  &quot;database_type&quot; integer(2),
        ///  &quot;workstation_name&quot; text(128),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;delete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240618 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for screw_bit_counter
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;screw_bit_counter&quot;;
        ///CREATE TABLE &quot;screw_bit_counter&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;mission_id&quot; integer NOT NULL,
        ///  &quot;bit_position&quot; integer NOT NULL,
        ///  &quot;max_num&quot; integer NOT NULL,
        ///  &quot;count_each_time&quot; integer NOT NULL,
        ///  &quot;current_counts&quot; integer NOT NULL,
        ///  &quot;clear_times&quot; integer NOT NULL,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240627 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;bar_code_matching_rule&quot; RENAME TO &quot;_bar_code_matching_rule_old_20240628&quot;;
        ///
        ///CREATE TABLE &quot;bar_code_matching_rule&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(64),
        ///  &quot;length&quot; integer(8),
        ///  &quot;end_char&quot; text(8),
        ///  &quot;key_position&quot; text(64),
        ///  &quot;key_char&quot; text(64),
        ///  &quot;type&quot; integer(2) NOT NULL,
        ///  &quot;mission_id&quot; integer,
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240628 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_bolt&quot; RENAME TO &quot;_product_bolt_old_20240822&quot;;
        ///
        ///CREATE TABLE &quot;product_bolt&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;side_id&quot; integer NOT NULL,
        ///  &quot;serial_num&quot; integer NOT NULL,
        ///  &quot;name&quot; text(128),
        ///  &quot;arranger_id&quot; integer,
        ///  &quot;specification&quot; real(16),
        ///  &quot;arranger_id2&quot; integer,
        ///  &quot;specification2&quot; real(16),
        ///  &quot;workstation_id&quot; integer,
        ///  &quot;position&quot; text(32),
        ///  &quot;location_x_percent&quot; real(8) NOT NULL,
        ///  &quot;location_y_percent&quot; real(8) NOT NULL,
        ///  &quot;setter_selector_id&quot; i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240822 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for mat_code_map_whyc
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;mat_code_map_whyc&quot;;
        ///CREATE TABLE &quot;mat_code_map_whyc&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;mat_code&quot; text(256) NOT NULL,
        ///  &quot;parameter_set&quot; integer(2) NOT NULL,
        ///  &quot;macs_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) NOT NULL,
        ///  &quot;modify [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240828 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20250315&quot;;
        ///
        ///CREATE TABLE &quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;predecessor_part_mission_ids&quot; text(256),
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;is_challenge_mission&quot; integer(1),
        ///  &quot;is_first_mission&quot; integer(1), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20250315 {
            get {
                return ResourceManager.GetString("modify_sqlite_20250315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- operation_data 表索引
        ///CREATE INDEX IF NOT EXISTS idx_operation_data_deleted_user_id ON operation_data(deleted, user_id, id);
        ///
        ///-- mission_record 表索引
        ///CREATE INDEX IF NOT EXISTS idx_mission_record_mission_id_parts ON mission_record(mission_id, parts_bar_code);
        ///CREATE INDEX IF NOT EXISTS idx_mission_record_deleted_time_mission ON mission_record(deleted, create_time, mission_id);.
        /// </summary>
        internal static string modify_sqlite_20250625 {
            get {
                return ResourceManager.GetString("modify_sqlite_20250625", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;main&quot;.&quot;Untitled&quot; (
        ///  &quot;id&quot; INTEGER(11) NOT NULL,
        ///  &quot;mission_record_id&quot; INTEGER(11),
        ///  &quot;parts_bar_code&quot; TEXT(255),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_time&quot; text(64) NOT NULL,
        ///  &quot;modify_time&quot; text(64) NOT NULL,
        ///  PRIMARY KEY (&quot;id&quot;)
        ///);
        ///
        ///ALTER TABLE &quot;main&quot;.&quot;device_io&quot; RENAME TO &quot;_device_io_old_20251023&quot;;
        ///
        ///CREATE TABLE &quot;main&quot;.&quot;device_io&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20251022 {
            get {
                return ResourceManager.GetString("modify_sqlite_20251022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for screw_bit_counter
        ///-- ----------------------------
        ///IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[screw_bit_counter]&apos;) AND type IN (&apos;U&apos;))
        ///	DROP TABLE [dbo].[screw_bit_counter]
        ///GO
        ///
        ///CREATE TABLE [dbo].[screw_bit_counter] (
        ///  [id] int  IDENTITY(1,1) NOT NULL,
        ///  [mission_id] int  NOT NULL,
        ///  [bit_position] int  NOT NULL,
        ///  [max_num] int  NOT NULL,
        ///  [count_each_time] int  NOT NULL,
        ///  [current_counts] int  NOT NULL, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlserver_20240627 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20240627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[bar_code_matching_rule] ADD [name] varchar(64) NULL
        ///.
        /// </summary>
        internal static string modify_sqlserver_20240628 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20240628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[product_bolt] ADD [parts_bar_code_ids] varchar(64) NULL
        ///.
        /// </summary>
        internal static string modify_sqlserver_20240822 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20240822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for mat_code_map_whyc
        ///-- ----------------------------
        ///IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[mat_code_map_whyc]&apos;) AND type IN (&apos;U&apos;))
        ///	DROP TABLE [dbo].[mat_code_map_whyc]
        ///GO
        ///
        ///CREATE TABLE [dbo].[mat_code_map_whyc] (
        ///  [id] int  IDENTITY(1,1) NOT NULL,
        ///  [mat_code] nvarchar(256) COLLATE Chinese_PRC_CI_AS  NOT NULL,
        ///  [parameter_set] int  NOT NULL,
        ///  [macs_id] int  NULL,
        ///  [user_id] int  NOT NULL,
        ///  [deleted [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlserver_20240828 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20240828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[product_mission] ADD [is_challenge_mission] int NULL;
        ///ALTER TABLE [dbo].[product_mission] ADD [is_first_mission] int NULL;
        ///ALTER TABLE [dbo].[product_mission] ADD [challenge_mission_id] int NULL;
        ///.
        /// </summary>
        internal static string modify_sqlserver_20250315 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20250315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- operation_data 表索引
        ///IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = &apos;idx_operation_data_deleted_user_id&apos; AND object_id = OBJECT_ID(&apos;operation_data&apos;))
        ///    CREATE INDEX idx_operation_data_deleted_user_id ON operation_data(deleted, user_id, id);
        ///GO
        ///
        ///-- mission_record 表索引
        ///IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = &apos;idx_mission_record_mission_id_parts&apos; AND object_id = OBJECT_ID(&apos;mission_record&apos;))
        ///    CREATE INDEX idx_mission_record_mission_id_parts ON mission_record(mission_id, parts_ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlserver_20250625 {
            get {
                return ResourceManager.GetString("modify_sqlserver_20250625", resourceCulture);
            }
        }
    }
}
