//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationGuidance_service.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperationGuidance_service.Database.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : AnengDB
        /// Source Server Type    : MySQL
        /// Source Server Version : 50744
        /// Source Host           : localhost:3307
        /// Source Schema         : aneng
        ///
        /// Target Server Type    : MySQL
        /// Target Server Version : 50744
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:44:48
        ///*/
        ///
        ///SET NAMES utf8mb4;
        ///SET FOREIGN_KEY_CHECKS = 0;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_mysql {
            get {
                return ResourceManager.GetString("init_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Navicat Premium Data Transfer
        ///
        /// Source Server         : SQLite
        /// Source Server Type    : SQLite
        /// Source Server Version : 3030001
        /// Source Schema         : main
        ///
        /// Target Server Type    : SQLite
        /// Target Server Version : 3030001
        /// File Encoding         : 65001
        ///
        /// Date: 31/03/2024 23:27:07
        ///*/
        ///
        ///PRAGMA foreign_keys = false;
        ///
        ///-- ----------------------------
        ///-- Table structure for bar_code_matching_rule
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS &quot;bar_code_matching_rule&quot;;
        ///CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_sqlite {
            get {
                return ResourceManager.GetString("init_sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `predecessor_mission_id` int NULL AFTER `macs_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240407 {
            get {
                return ResourceManager.GetString("modify_mysql_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_mission` 
        ///  ADD COLUMN `multi_device_independence` int(1) NULL AFTER `predecessor_mission_id`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240413 {
            get {
                return ResourceManager.GetString("modify_mysql_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE `product_side` 
        ///  ADD COLUMN `cropped` int(1) NULL AFTER `rotate_angle`;
        ///.
        /// </summary>
        internal static string modify_mysql_20240510 {
            get {
                return ResourceManager.GetString("modify_mysql_20240510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;main&quot;.&quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240407&quot;;
        ///
        ///CREATE TABLE &quot;main&quot;.&quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot;modifier&quot; text(128) NOT NULL,
        ///  &quot;create_ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240407 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;main&quot;.&quot;product_mission&quot; RENAME TO &quot;_product_mission_old_20240413&quot;;
        ///
        ///CREATE TABLE &quot;main&quot;.&quot;product_mission&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;pn_code&quot; text(64),
        ///  &quot;max_ng_num&quot; integer(4),
        ///  &quot;password_need_time&quot; integer(4),
        ///  &quot;enabled&quot; integer(1),
        ///  &quot;macs_id&quot; integer,
        ///  &quot;predecessor_mission_id&quot; integer,
        ///  &quot;multi_device_independence&quot; integer(1),
        ///  &quot;user_id&quot; integer NOT NULL,
        ///  &quot;deleted&quot; integer(1) NOT NULL,
        ///  &quot;creator&quot; text(128) NOT NULL,
        ///  &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240413 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;main&quot;.&quot;product_side&quot; RENAME TO &quot;_product_side_old_20240510&quot;;
        ///
        ///CREATE TABLE &quot;main&quot;.&quot;product_side&quot; (
        ///  &quot;id&quot; integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  &quot;name&quot; text(128),
        ///  &quot;mission_id&quot; integer,
        ///  &quot;image&quot; text(256),
        ///  &quot;max_rectangle_width&quot; integer(16),
        ///  &quot;max_rectangle_height&quot; integer(16),
        ///  &quot;max_rectangle_location&quot; text(32),
        ///  &quot;center_location&quot; text(32),
        ///  &quot;location_offset&quot; text(32),
        ///  &quot;location_offset_moving&quot; text(32),
        ///  &quot;zooming_ratio&quot; real(8),
        ///  &quot;zooming_ratio_extra&quot; real(8),
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modify_sqlite_20240510 {
            get {
                return ResourceManager.GetString("modify_sqlite_20240510", resourceCulture);
            }
        }
    }
}
